blank_issues_enabled: false
contact_links:
  - name: AI Gita Discussion
    url: https://github.com/jkgcg/AI-Gita/discussions
    about: Use discussions for open-ended ideas and non-actionable questions.
